#!/bin/bash
#sudo wget -O - https://abcd567a.github.io/kali/KEY.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/abcd567a-archive-keyring.gpg > /dev/null
wget -O /etc/apt/trusted.gpg.d/abcd567a-archive-keyring.gpg https://abcd567a.github.io/kali/KEY2.gpg
